# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
    access_control:
        - { path: ^/orders/admin/, role: ROLE_ADMIN }
        - { path: ^/foods/admin/, role: ROLE_ADMIN }
        - { path: ^/address, role: ROLE_USER }
        - { path: ^/address/, role: ROLE_USER }
        - { path: ^/cart/, role: ROLE_USER }
        - { path: ^/orders/, role: ROLE_USER }
        - { path: ^/foods/, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    role_hierarchy:
            ROLE_CONTRIBUTOR: ROLE_USER
            ROLE_MODERATOR:   ROLE_CONTRIBUTOR
            ROLE_ADMIN:       ROLE_MODERATOR
            ROLE_SUPER_ADMIN: ROLE_ADMIN