# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.user_service:
    class: AppBundle\Service\UserService
    arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@app.password_encoder"]
  app.password_encoder:
    class: AppBundle\Service\PasswordEncoderService
  app.address_service:
      class: AppBundle\Service\AddressService
      arguments: ["@doctrine.orm.entity_manager", "@form.factory"]
  app.food_service:
      class: AppBundle\Service\FoodService
      arguments: ['@doctrine.orm.entity_manager', '@form.factory']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
